/gauge_reader:
  gauge_reader:
    ros__parameters:
      qos_overrides:
        /gauge_reading:
          publisher:
            reliability: reliable
            history: keep_last
            depth: 10
        /detections:
          subscription:
            reliability: reliable
            history: keep_last
            depth: 10
      image_stream:
        reliability: reliable
        history: keep_last
        depth: 10

